version: '2'
services:
  realestatemanagementservice-app:
    image: realestatemanagementservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://realestatemanagementservice-mssql:1433;database=RealEstateManagementService
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  realestatemanagementservice-mssql:
    extends:
      file: mssql.yml
      service: realestatemanagementservice-mssql
